import {UserId, User} from "@/types/user.types";
import {ChatId, Chat} from "@/types/chat.types";
import {CallId, Call} from "@/types/call.types";
import {MessageId, Message} from "@/types/message.types";

export const MOCK_USERS: Record<UserId, User> = {
  u1: {
    id: 'u1',
    username: 'alice',
    displayName: 'Alice',
    avatarUrl: 'https://example.com/avatar1.png',
    status: 'online',
    lastSeenAt: Date.now(),
    createdAt: Date.now(),
  },
  u2: {
    id: 'u2',
    username: 'bob',
    displayName: 'Bob',
    avatarUrl: 'https://example.com/avatar2.png',
    status: 'online',
    lastSeenAt: Date.now(),
    createdAt: Date.now(),
  },
  u3: {
    id: 'u3',
    username: 'charlie',
    displayName: 'Charlie',
    avatarUrl: 'https://example.com/avatar3.png',
    status: 'away',
    lastSeenAt: Date.now() - 1000 * 60 * 10, // 10 мин назад
    createdAt: Date.now(),
  },
};

export const MOCK_CHATS: Record<ChatId, Chat> = {
  "c1": {
    id: "c1",
    type: "direct",
    peerId: "u1",
    lastMessageId: "m1",
    updatedAt: Date.now(),
    unreadCount: 2,
  },
  "c2": {
    id: "c2",
    type: "direct",
    peerId: "u3",
    lastMessageId: "m4",
    updatedAt: Date.now(),
    unreadCount: 0,
  },
  "c3": {
    id: "c3",
    type: "group",
    name: "Mobile Dev Team",
    avatarUrl: "https://example.com/group1.png",
    participants: [
      { userId: "u1", role: "owner", joinedAt: Date.now() },
      { userId: "u2", role: "admin", joinedAt: Date.now() },
      { userId: "u3", role: "member", joinedAt: Date.now() },
    ],
    lastMessageId: "m7",
    updatedAt: Date.now(),
    unreadCount: 1,
  },
}

export const MOCK_MESSAGES: Record<MessageId, Message> = {
  m1: {
    id: 'm1',
    chatId: 'c1',
    senderId: 'u1',
    type: 'text',
    text: 'Hi Bob, how’s the app going?',
    createdAt: Date.now() - 1000 * 60 * 60 * 2,
    deletedAt: null,
    isEdited: false,
    isPinned: false,
    reactions: [],
    linkPreviews: [],
  },
  m2: {
    id: 'm2',
    chatId: 'c1',
    senderId: 'u2',
    type: 'voice',
    file: {
      id: 'f1',
      url: 'https://example.com/voice1.opus',
      fileName: 'voice1.opus',
      mimeType: 'audio/opus',
      size: 1024 * 200, // 200 Kb
      durationSec: 12,
    },
    createdAt: Date.now() - 1000 * 60 * 60,
    deletedAt: null,
    isEdited: false,
    isPinned: false,
    reactions: [],
  },
  m3: {
    id: 'm3',
    chatId: 'c1',
    senderId: 'u1',
    type: 'video',
    file: {
      id: 'f2',
      url: 'https://example.com/video1.mp4',
      fileName: 'video1.mp4',
      mimeType: 'video/mp4',
      size: 1024 * 1024 * 5, // 5 Mb
      durationSec: 45,
    },
    thumbnailUrl: 'https://example.com/video1_thumb.png',
    createdAt: Date.now() - 1000 * 60 * 50,
    deletedAt: null,
    isEdited: false,
    isPinned: false,
    reactions: [],
  },
  m4: {
    id: 'm4',
    chatId: 'c2',
    senderId: 'u3',
    type: 'text',
    text: 'Hey, do you want to join the team chat?',
    createdAt: Date.now() - 1000 * 60 * 30,
    deletedAt: null,
    isEdited: false,
    isPinned: false,
    reactions: [],
    linkPreviews: [],
  },
  m5: {
    id: 'm5',
    chatId: 'c3',
    senderId: 'u1',
    type: 'text',
    text: 'Let’s start the sprint planning.',
    createdAt: Date.now() - 1000 * 60 * 20,
    deletedAt: null,
    isEdited: false,
    isPinned: false,
    reactions: [{ emoji: '👋', userId: 'u2', createdAt: Date.now() }],
    linkPreviews: [],
  },
  m6: {
    id: 'm6',
    chatId: 'c3',
    senderId: 'u2',
    type: 'link',
    linkPreview: {
      url: 'https://example.com/sprint-board',
      title: 'Sprint Board',
      description: 'Our current sprint tasks',
      imageUrl: null,
    },
    createdAt: Date.now() - 1000 * 60 * 15,
    deletedAt: null,
    isEdited: false,
    isPinned: false,
    reactions: [],
  },
  m7: {
    id: 'm7',
    chatId: 'c3',
    senderId: 'u3',
    type: 'reply',
    text: 'Fine, I’ll add it to the backlog.',
    replyTo: {
      messageId: 'm5',
      chatId: 'c3',
      senderId: 'u1',
      text: 'Let’s start the sprint planning.',
    },
    createdAt: Date.now() - 1000 * 60 * 10,
    deletedAt: null,
    isEdited: false,
    isPinned: false,
    reactions: [],
    linkPreviews: [],
  },
};

export const MOCK_CALLS: Record<CallId, Call> = {
  call1: {
    id: 'call1',
    type: 'audioVideo',
    status: 'ended',
    initiatorId: 'u1',
    participants: [
      { userId: 'u1', joinedAt: Date.now() - 1000 * 60 * 5, durationSec: 300 },
      { userId: 'u2', joinedAt: Date.now() - 1000 * 60 * 4, durationSec: 240 },
    ],
    chatId: 'c1',
    startedAt: Date.now() - 1000 * 60 * 5,
    endedAt: Date.now() - 1000 * 60 * 2,
    durationSec: 180,
    isGroup: false,
  },
  call2: {
    id: 'call2',
    type: 'audio',
    status: 'ended',
    initiatorId: 'u3',
    participants: [
      { userId: 'u1', joinedAt: Date.now() - 1000 * 60 * 10, durationSec: 600 },
      { userId: 'u2', joinedAt: Date.now() - 1000 * 60 * 8, durationSec: 480 },
      { userId: 'u3', joinedAt: Date.now() - 1000 * 60 * 10, durationSec: 600 },
    ],
    chatId: 'c3',
    startedAt: Date.now() - 1000 * 60 * 10,
    endedAt: Date.now() - 1000 * 60 * 4,
    durationSec: 360,
    isGroup: true,
  },
};