import type {UserChatListItemType} from "@/types/ChatListTypes.ts"

export const DATA: UserChatListItemType[] = [
  {
    id: '1',
    name: 'John Alan',
    avatar: '',
    avatarStatus: true,
    message: 'Hello world',
    time: '22:00',
    isSender: true,
    type: 'message',
  },
  {
    id: '2',
    name: 'Micky Thomson',
    avatar: '',
    avatarStatus: false,
    message: 'Hi there!',
    time: '22:50',
    isSender: false,
    type: 'message',
  },
  {
    id: '3',
    name: 'Alice Cooper',
    avatar: '',
    avatarStatus: true,
    file: 'photo',
    time: '21:50',
    isSender: true,
    type: 'file',
  },
  {
    id: '4',
    name: 'James Cameron',
    avatar: '',
    avatarStatus: true,
    file: 'video',
    time: '11:30',
    isSender: false,
    type: 'file',
  },
  {
    id: '5',
    name: 'Mellisa Davis',
    avatar: '',
    avatarStatus: true,
    file: 'video',
    message: 'See video',
    time: '11:36',
    isSender: false,
    type: 'fileMessage',
  },
  {
    id: '6',
    name: 'John Smith',
    avatar: '',
    avatarStatus: true,
    file: 'photo',
    message: 'Im in spain',
    time: '13:33',
    isSender: false,
    type: 'fileMessage',
  },
];